### ISSUE TITLE
Error when executing the Colab notebook

### ISSUE THREAD

**Issue by sophamma** [VSAnimator/Sketch-a-Sketch#5]
Hello,
I've been running into the following issue, which seems to be related to Gradio:

```py
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-35f22ea0f475>](https://6eetd6pmas5-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231215-060140_RC00_591195218#) in <cell line: 15>()
     21     with gr.Row():
     22         with gr.Column(scale = 1):
---> 23             with gr.Tabs(shape=(768, 768),min_width=512):
     24                 with gr.TabItem("Sketch", shape=(512, 512),min_width=512):
     25                     i = gr.Image(source="canvas", shape=(512, 512), tool="color-sketch",

[/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py](https://6eetd6pmas5-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231215-060140_RC00_591195218#) in wrapper(*args, **kwargs)
    153             return None
    154         else:
--> 155             return fn(self, **kwargs)
    156 
    157     return wrapper

TypeError: Tabs.__init__() got an unexpected keyword argument 'shape'
```

This issue occurred both in the Colab notebook (running on GPUs / T4) and locally on my Windows computer.
Especially, the Colab notebook should work out of the box, so it would be great if you could look into this, please.
It would be helpful if you could guide me on how to solve this. Do the dependencies in the requirements.txt file need to be updated to specify versions of the libraries?
Just to let you know, the Hugging Face space is down as well.

Thank you in advance for your help!

**Comment by VSAnimator** [comment]
Apologies, it appears that there have been some significant changes with the introduction of Gradio 4.0. I've updated the requirements to reflect that this should run on Gradio 3, HF/Colab/etc. should work now!
